// AUTO-GENERATED by scripts/gen-companion-config.js from package.json (publisher: "HimanshuShekhar", name: "codeforces-inline").
// Do not edit by hand — re-run "npm run gen:companion-config" instead.
// Loaded by both content.js (page context) and background.js (importScripts).
var CF_DEEPLINK = {
    uriBase: 'vscode://HimanshuShekhar.codeforces-inline',
    marketplaceUrl: 'https://marketplace.visualstudio.com/items?itemName=HimanshuShekhar.codeforces-inline'
};
